const express = require('express');
const cors = require('cors');
const authRoutes = require('./routes/authRoutes');
const clienteRoutes = require('./routes/clienteRoutes');
const usuarioRoutes = require('./routes/usuarioRoutes');
const osRoutes = require('./routes/osRoutes');
const estoqueRoutes = require('./routes/estoqueRoutes');
const relatorioRoutes = require('./routes/relatorioRoutes');
const auditoriaRoutes = require('./routes/auditoriaRoutes');
const app = express();
app.use(cors());
app.use(express.json({ limit: '20mb' }));
app.get('/api/health', (_req, res) => res.json({ ok: true }));
app.use('/api/auth', authRoutes);
app.use('/api/clientes', clienteRoutes);
app.use('/api/usuarios', usuarioRoutes);
app.use('/api/os', osRoutes);
app.use('/api/estoque', estoqueRoutes);
app.use('/api/relatorios', relatorioRoutes);
app.use('/api/auditoria', auditoriaRoutes);
module.exports = app;
