const express = require('express');
const router = express.Router();
const auth = require('../middlewares/authMiddleware');
const { permit } = require('../middlewares/authMiddleware');
const c = require('../controllers/clienteController');
router.post('/', auth, permit('admin','atendente'), c.criarCliente);
router.get('/', auth, permit('admin','atendente','tecnico'), c.listarClientes);
router.get('/:id', auth, permit('admin','atendente','tecnico'), c.buscarClientePorId);
router.put('/:id', auth, permit('admin','atendente'), c.atualizarCliente);
router.delete('/:id', auth, permit('admin'), c.deletarCliente);
module.exports = router;
