const express = require('express');
const router = express.Router();
const auth = require('../middlewares/authMiddleware');
const { permit } = require('../middlewares/authMiddleware');
const o = require('../controllers/osController');
router.get('/publica/:codigo', o.buscarOSPublica);
router.post('/', auth, permit('admin','atendente'), o.criarOS);
router.get('/', auth, permit('admin','atendente','tecnico','financeiro'), o.listarOS);
router.get('/:id', auth, permit('admin','atendente','tecnico','financeiro'), o.buscarOSPorId);
router.get('/:id/imprimir', o.imprimirOS);
router.get('/:id/qr', auth, permit('admin','atendente','tecnico','financeiro'), o.qrOS);
router.put('/:id', auth, permit('admin','atendente'), o.atualizarOS);
router.patch('/:id/status', auth, permit('admin','tecnico','atendente'), o.atualizarStatusOS);
router.patch('/:id/diagnostico', auth, permit('admin','tecnico'), o.salvarDiagnostico);
router.patch('/:id/orcamento', auth, permit('admin','tecnico','atendente'), o.salvarOrcamento);
router.get('/:id/whatsapp/avaliacao', auth, permit('admin','tecnico','atendente'), o.gerarWhatsAppAvaliacao);
router.post('/:id/whatsapp/avaliacao/enviar', auth, permit('admin','tecnico','atendente'), o.enviarWhatsAppAvaliacao);
router.patch('/:id/orcamento/aprovacao', auth, permit('admin','atendente'), o.aprovarOrcamento);
router.post('/:id/pecas', auth, permit('admin','tecnico'), o.adicionarPeca);
router.put('/:id/pecas/:id_peca', auth, permit('admin','tecnico'), o.atualizarPeca);
router.delete('/:id/pecas/:id_peca', auth, permit('admin','tecnico'), o.removerPeca);
router.patch('/:id/servico', auth, permit('admin','tecnico'), o.salvarServico);
router.patch('/:id/pagamento', auth, permit('admin','financeiro'), o.salvarPagamento);
router.patch('/:id/entrega', auth, permit('admin','atendente'), o.salvarEntrega);
router.patch('/:id/checklist/:tipo', auth, permit('admin','atendente','tecnico'), o.salvarChecklist);
router.patch('/:id/garantia', auth, permit('admin','atendente'), o.salvarGarantia);
router.post('/:id/reabrir', auth, permit('admin','atendente','tecnico'), o.reabrirOS);
router.delete('/:id', auth, permit('admin'), o.deletarOS);
module.exports = router;
